name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Build and Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install --package-lock-only --no-audit --no-fund --omit=optional

      - name: Build
        run: npm run build
        env:
          CI: false

      - name: Run code lint check
        run: npm run lint
